### ISSUE TITLE
Goto Definition from JSX to component

### ISSUE THREAD

**Issue by r03** [borela/naomi#147]
Hey, 

I would first like to say that I really like your package.
My react code (with fragments, ligatures, flow, es6, ..) looks really good now thanks to you.

The only thing I'm missing is to jump from JSX code to the used component.
Below is a simple example of a component. It would be great if I could simple navigate to the Input or Label component with Goto Definition.

Is this something that this package could do? Or should this be done by a different package?
Or maybe this can't be done?

```
import * as React from "react";
import {uniqueId} from "lodash";
import {Label} from "./core/Label";
import {Input} from "./core/Input";

const InputWithLabel = ({text, value, onChange, children}) => {

    const id = uniqueId("id_")
    let label = children
    if (!label) label = text + ':'

    return <>
        <Label htmlFor={id}>{label}</Label>
        <Input id={id}
               type={type}
               value={value}
               onChange={onChange}
               placeholder={text}/>
    </>
}
```

**Comment by borela** [comment]
I believe this is possible to implement and I love the idea, I'll do some tests locally.

**Comment by borela** [comment]
I pushed a patch with that feature. The file responsible for the indexing of JSX components is this one:
https://github.com/borela/naomi/blob/master/preferences/jsx/symbol-components.tmPreferences

but I normally code in YAML format like this:
https://github.com/borela/naomi/blob/master/preferences/jsx/symbol-components.YAML-tmPreferences

And compile it to the tmPreferences using https://packagecontrol.io/packages/PackageDev
If you want to tweak the settings locally, you can ignore the yaml file and just edit the tmPreferences file.

**Comment by borela** [comment]
O now I see what you are talking, I thought it was just about navigation in the current file (Ctrl + R). I'll investigate further if it's possible to implement that.

**Comment by borela** [comment]
It looks like it's possible to implement in the plugin system, I'll finish the build system first to make the syntaxes less memory hungry and try to implement this one aftewards.

**Comment by r03** [comment]
Thanks!
I now also found this plugin: https://github.com/pichillilorenzo/JavaScriptEnhancements
With this the Goto Definition seems to work and I have better code completion.
Will this plugin conflict with your plugin?
For now I'm using both because I like your theme and support for flow/es6/react syntax and the other plugin for making sublime smarter for javascript.

**Comment by borela** [comment]
Even better that a solution already exists, no problem between the two that I can think of, my main focus on this repo are the syntaxes not competitions because people might have their own snippets.  I'll just make sure they are always compatible then :D

Does the JSX go to definition works too?

**Comment by r03** [comment]
It did work. For some reason it stopped working. I need to investigate this but this is not a problem in your plug-in. Thanks!

**Comment by wonderfool** [comment]
I'm a year late to the game but in case it helps anyone looking for *"Go To Definition"* functionality in *JavaScriptEnhancements* -

It looks like the *JavaScriptEnhancements* command `go_to_def` wasn't working because:

* The contents of the current view were being copied to a temp file allocated by the OS. 
* The temp file was the input argument to `flow get-def`.
* The import paths were being evaluated relative to the temp file, which meant they resolved to nothing. 

I got it working by editing `/src/libs/flow/flow_cli.py` in the Sublime package itself to replace this:

```python
def get_def(self, options=[], **kwargs):

  deps = self.parse_cli_dependencies(self.view, **kwargs)

  node = NodeJS(check_local=True)
  
  result = node.execute_check_output(
    self.flow_cli,
    [
      'get-def',
      '--from', 'sublime_text',
      '--root', deps.project_root,
      '--json',
      ':temp_file',
      str(deps.row + 1), str(deps.col + 1)
    ] + options,
    is_from_bin=self.is_from_bin,
    use_fp_temp=True, 
    fp_temp_contents=deps.contents, 
    is_output_json=True,
    use_only_filename_view_flow=True,
    chdir=self.chdir,
    bin_path=self.bin_path,
    use_node=self.use_node,
    clean_output_flow=True
  )

  return result
```

...with this: 

```python
def get_def(self, options=[], **kwargs):

  deps = self.parse_cli_dependencies(self.view, **kwargs)

  node = NodeJS(check_local=True)

  result = node.execute_check_output(
    self.flow_cli,
    [
      'get-def',
      '--from', 'sublime_text',
      '--root', deps.project_root,
      '--path', self.view.file_name(),
      '--json',
      str(deps.row + 1), str(deps.col + 1)
    ] + options,
    is_from_bin=self.is_from_bin,
    use_fp_temp=True,
    fp_temp_contents=deps.contents,
    is_output_json=True,
    use_only_filename_view_flow=False,
    chdir=self.chdir,
    bin_path=self.bin_path,
    use_node=self.use_node,
    clean_output_flow=True
  )

  return result
```

...where:

* `use_only_filename_view_flow` is changed to `False`, which causes `NodeJS.execute_check_output` to redirect the temp file's contents into `stdin` of `flow` instead of giving `flow` the temp file itself.
* `--path` is set to `self.view.file_name()` - this instructs `flow` to pretend the redirected `stdin` content exists at the original source file's location.  This allows the imports in the temp file to resolve correctly. 

No idea why it was working before or what changed.  I just installed *JavaScriptEnhancements* for the first time today.
