### ISSUE TITLE
Comment is not allowed before default value in function definition

### ISSUE THREAD

**Issue by StreetStrider** [borela/naomi#166]
Found a minor thing. Looks like comment is not allowed inside round brackets in function definition it is before default value.
```js
function f (x /**/ = 1) { var y = 2 }
```
Where `var` is destyled.
I tried to feed that to Node and it works OK, so I presume the syntax is correct, thus highlighting must follow.

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v4.1.3;

For now, the [logic around parameters](https://github.com/borela/naomi/blob/a1211739ec72f0f0ed428aac11775a9cb40b24e1/syntaxes/fjsx15/function/parameter/simple.sublime-syntax#L103) is a bit complex because I am enveloping the parameter and default value with the scope `meta.function.parameter.optional` but I am not sure this meta scope is necessary.

**Comment by StreetStrider** [comment]
:+1:
