### ISSUE TITLE
Object's fields have suspicious color

### ISSUE THREAD

**Issue by YuriGor** [borela/naomi#176]
test code:
```javascript
var obj = {
  hi:"there",
  count:0,
  really:true,
  mean:undefined,
  nono:null,
  method:function(){}
};
```
first lets look at native JS syntax
monokai:
![image](https://user-images.githubusercontent.com/6861317/46827739-1f666380-cda2-11e8-9c06-a4618a4e8b8a.png)
candyman:
![image](https://user-images.githubusercontent.com/6861317/46827778-33aa6080-cda2-11e8-98fa-bff202466ff3.png)
field names are nearly white, let's say it's a basic text color
And this is Naomi
monokai:
![image](https://user-images.githubusercontent.com/6861317/46827905-84ba5480-cda2-11e8-8af4-efb97b7965ae.png)
candyman:
![image](https://user-images.githubusercontent.com/6861317/46827944-98fe5180-cda2-11e8-9cba-0722e0be6026.png)
in monokai it same as string constants
in candyman I am not sure what does this color mean.
Was this made intentionally?
In monokai this looks not very good with large objects filled with strings:
![image](https://user-images.githubusercontent.com/6861317/46828128-23df4c00-cda3-11e8-9e42-bcf171b9f454.png)
everything is yellow, not very readable.

**Comment by YuriGor** [comment]
Also I found same issue in the babel repo:
https://github.com/babel/babel-sublime/issues/352
and with marianna scheme there is same problem
native js:
![image](https://user-images.githubusercontent.com/6861317/46829157-b41e9080-cda5-11e8-91e9-3c34b8737971.png)
Naomi:
![image](https://user-images.githubusercontent.com/6861317/46829177-c4cf0680-cda5-11e8-93af-bd61a194ac87.png)

**Comment by borela** [comment]
This was intentionally, Naomi marks then as:

```
meta.object-literal.js.fjsx15
meta.block.js.fjsx15
meta.object-literal.key.js.fjsx15
string.unquoted.js.fjsx15
```

While the native syntax only does:

```
meta.object-literal.js
meta.object-literal.key.js
```

This was intentional in Naomi because it keeps the syntax compatible with most color schemes that like Candyman gives a different color to object literal keys, in fact, on the build system's branch I changed the keys colors to a light brown to distinguish better the key from types in code that has a lot of [Flow](https://flow.org/) annotations:

![image](https://user-images.githubusercontent.com/11317458/46839708-9cd7a700-cd95-11e8-8067-5b3d29a09e29.png)

The way the native syntax scopes the keys, makes it imposible to color it without affecting other key types.

**Comment by borela** [comment]
If you add a rule to your color scheme targeting the scopes:

```
meta.object-literal.key
string.unquoted
```

You'll be able to use any color in there without the risk of affecting the values.

**Comment by YuriGor** [comment]
So it's more like monokai's issue. 
I added scope as you suggested, it works, thank you.

**Comment by borela** [comment]
No problem, if you have any questions, feel free to open new issue reports :D
