### ISSUE TITLE
JSX closing tags don't match style

### ISSUE THREAD

**Issue by AlexKvazos** [borela/naomi#56]
The opening and closing div tags have a different color and it is pretty annoying coming from the babel syntax to see this change.

![screen shot 2018-01-30 at 4 27 27 pm](https://user-images.githubusercontent.com/4448627/35594930-98c19122-05da-11e8-922b-47d4d72d8db1.png)

**Comment by borela** [comment]
What color scheme are you using?

**Comment by borela** [comment]
It was a bug in the syntax, in the develop branch I already patched it, I will release the patch.

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.3.4

**Comment by AlexKvazos** [comment]
Omg this was one hell of a fast response. Thank you very much! Definitely sticking with FXJS15 for now.

Why not contribute to babel for the jsx/javascript syntax? Sublime's community is not as big as it was and having two definitions just makes it worse.

**Comment by borela** [comment]
You are welcome :D 
I considered it but babel sublime is trying to support atom too, so they require that you code it using the tmLanguage instead of the sublime syntax definitions https://github.com/borela/naomi/issues/21 some of the features I use don't exist in the tmLanguage. 

Sublime syntaxes are not without its flaws https://github.com/borela/naomi/issues/25 I still can't predict multi line arrow functions, but as far as I know, tmLanguage has this limitation too.
