### ISSUE TITLE
Flow plugin autocompletion didn't work

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#59]
I use [flow-builtin-type-completion](https://github.com/xinchaobeta/flow-builtin-type-completion) and it didn't work with FJSX15 because [code](https://github.com/xinchaobeta/flow-builtin-type-completion/blob/master/main.py#L12)

How do you think which will be right: send PR for flow-builtin-type-completion or change your base scope name?

I suppose that it's not only one plugin which depends from `source.js` scope name

**Comment by borela** [comment]
I think I can change the main scope to `source.js`, but one problem that I can think of is that the default JavaScript package would be overriden, this means that if you try to highlight HTML with the default syntax instead of the one I wrote (HTML 5), it would not work perfectly because I tend to pop contexts.

I'll check the compatibility with HTML and CSS and see if it is possible to do it without breaking the default syntaxes.

**Comment by borela** [comment]
I did some changes to the syntax to integrate it with the core and add support for plugins like the one you mentioned.

You can try the beta https://github.com/borela/naomi/releases/tag/v3.4.0-beta and see if works without issues. Don't forget to restart sublime, it will override the core JavaScript and CSS on the HTML syntaxes.

**Comment by borela** [comment]
Released the patch: https://github.com/borela/naomi/releases/tag/v3.4.0 and it has proper integration with the core syntaxes now.

**Comment by max-mykhailenko** [comment]
All works fine. Thanks!
